export type GeneratedHtmlSecurityIssue =
  | "禁止的 HTML 标签"
  | "禁止的属性或事件处理器"
  | "本地、临时或内嵌资源地址";

const FORBIDDEN_TAG = /<(?:script|style|iframe|object|embed|base|form|noscript|template|svg|canvas)\b/i;
const TAG_PATTERN = /<[^>]*>/g;
const ATTRIBUTE_PATTERN = /([:\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/gi;
const ALLOWED_ORIGIN_ATTRIBUTES = new Set([
  "data-fantastic-clipboard",
  "data-fantastic-plain-length",
  "data-fantastic-plain-hash",
]);

function isUnsafeResource(value: string): boolean {
  const trimmed = value.trim();
  if (/^(?:file|blob|data|app|fantastic-asset):/i.test(trimmed)) return true;
  if (/^(?:https?:\/\/)?(?:localhost|127(?:\.\d{1,3}){3}|0\.0\.0\.0|\[::1\])(?::\d+)?(?:[/?#]|$)/i.test(trimmed)) return true;
  return false;
}

/**
 * Audits HTML generated by this application only. It is not an external HTML
 * sanitizer and must never be used to decide whether untrusted clipboard HTML
 * is safe to consume.
 */
export function auditGeneratedHtmlMarkup(html: string): GeneratedHtmlSecurityIssue[] {
  const issues = new Set<GeneratedHtmlSecurityIssue>();
  const markup = html.match(TAG_PATTERN) ?? [];
  for (const tag of markup) {
    if (FORBIDDEN_TAG.test(tag)) issues.add("禁止的 HTML 标签");
    for (const match of tag.matchAll(ATTRIBUTE_PATTERN)) {
      const name = (match[1] ?? "").toLowerCase();
      const value = match[2] ?? match[3] ?? match[4] ?? "";
      const classAllowed = name === "class" && /^language-[a-z0-9_+-]+(?:\s+language-[a-z0-9_+-]+)*$/i.test(value);
      if (/^on[a-z]/i.test(name) || (name === "class" && !classAllowed) || name === "id" || (name.startsWith("data-") && !ALLOWED_ORIGIN_ATTRIBUTES.has(name))) {
        issues.add("禁止的属性或事件处理器");
      }
      if ((name === "src" || name === "href" || name === "action" || name === "poster" || name === "style") && isUnsafeResource(value)) {
        issues.add("本地、临时或内嵌资源地址");
      }
      if (name === "style" && /url\s*\(\s*(?:file|blob|data|app|fantastic-asset):/i.test(value)) {
        issues.add("本地、临时或内嵌资源地址");
      }
      if (/\b(?:file|blob|data|app|fantastic-asset):/i.test(value)) {
        issues.add("本地、临时或内嵌资源地址");
      }
    }
  }
  return [...issues];
}

export const auditWechatHtmlMarkup = auditGeneratedHtmlMarkup;
