export const IPC_CHANNELS = {
  openMarkdownFile: "file:open-markdown",
  listRecentFiles: "file:list-recent",
  openRecentFile: "file:open-recent",
  createUntitledFile: "file:create-untitled",
  readClipboard: "clipboard:read-text-html",
  openDroppedMarkdownFile: "file:open-dropped-markdown",
  listExternalOpenRequests: "file:list-external-open-requests",
  openExternalFile: "file:open-external",
  discardExternalOpenRequest: "file:discard-external-open-request",
  activateFileSession: "file:activate-session",
  closeFileSession: "file:close-session",
  persistRecoverySession: "recovery:persist-session",
  restoreRecoverySession: "recovery:restore-session",
  openWorkspaceFolder: "workspace:open-folder",
  openWorkspaceFile: "workspace:open-file",
  renameWorkspaceFile: "workspace:rename-file",
  renameOpenFile: "file:rename-open",
  saveCurrentFile: "file:save-current",
  saveCurrentFileAs: "file:save-current-as",
  checkExternalFileChange: "file:check-external-change",
  selectAndImportImages: "image:select-and-import",
  importDroppedImages: "image:import-dropped",
  selectAndInstallFont: "font:select-and-install",
  commitParse: "document:commit-parse",
  resolveResources: "resource:resolve",
  previewDerivedUpdate: "preview:derived-update",
  beginOutput: "output:begin",
  approveOutputOmissions: "output:approve-omissions",
  cancelOutput: "output:cancel",
  copyWechatReplacement: "output:wechat-copy-replacement",
  createWechatDraft: "output:wechat-create-draft",
  publishWechatArticle: "output:wechat-publish-article",
  getWechatApiConfig: "config:wechat-api-get",
  testWechatApiConnection: "config:wechat-api-test-connection",
  saveWechatApiConfig: "config:wechat-api-save",
  selectWechatCover: "config:wechat-cover-select",
  clearWechatApiConfig: "config:wechat-api-clear",
  saveWechatAcceptanceReport: "output:wechat-save-acceptance-report",
  listWechatThemes: "theme:wechat-list",
  resolveWechatThemeForPreview: "theme:wechat-resolve-preview",
  saveWechatThemeAsCustom: "theme:wechat-save-custom",
  deleteWechatTheme: "theme:wechat-delete",
  exportWechatTheme: "theme:wechat-export",
  importWechatTheme: "theme:wechat-import",
  detectAiProvider: "ai:detect-provider",
  invokeAi: "ai:invoke",
  suggestWechatTheme: "ai:suggest-wechat-theme",
  cancelAi: "ai:cancel",
  aiInvocationEvent: "ai:invocation-event",
  getDeepSeekConfig: "ai:deepseek-config-get",
  saveDeepSeekConfig: "ai:deepseek-config-save",
  clearDeepSeekConfig: "ai:deepseek-config-clear",
  testDeepSeekConnection: "ai:deepseek-config-test",
  getGeminiConfig: "ai:gemini-config-get",
  saveGeminiConfig: "ai:gemini-config-save",
  clearGeminiConfig: "ai:gemini-config-clear",
  testGeminiConnection: "ai:gemini-config-test",
  getKimiConfig: "ai:kimi-config-get",
  saveKimiConfig: "ai:kimi-config-save",
  clearKimiConfig: "ai:kimi-config-clear",
  testKimiConnection: "ai:kimi-config-test",
  getMiniMaxConfig: "ai:minimax-config-get",
  saveMiniMaxConfig: "ai:minimax-config-save",
  clearMiniMaxConfig: "ai:minimax-config-clear",
  testMiniMaxConnection: "ai:minimax-config-test",
  getOpenAiCompatibleConfig: "ai:openai-compatible-config-get",
  saveOpenAiCompatibleConfig: "ai:openai-compatible-config-save",
  clearOpenAiCompatibleConfig: "ai:openai-compatible-config-clear",
  listOpenAiCompatibleModels: "ai:openai-compatible-models-list",
  testOpenAiCompatibleConnection: "ai:openai-compatible-config-test",
  listDocumentHistory: "history:list",
  restoreDocumentHistory: "history:restore",
  showOpenFileMenu: "file:menu",
  showWorkspaceFileMenu: "workspace:file-menu",
  savePreviewAsset: "asset:save",
} as const;

export const FANTASTIC_EDITOR_LIMITS = Object.freeze({
  maxSourceCharacters: 10_000_000,
  maxMarkdownFileBytes: 40 * 1024 * 1024,
  maxResourceReferences: 10_000,
  maxSingleResourceBytes: 50 * 1024 * 1024,
  maxUniqueResolutionBytes: 200 * 1024 * 1024,
  maxFormulaRendersPerOutput: 500,
  maxMermaidRendersPerOutput: 100,
});
