export const IPC_CHANNELS = {
  openMarkdownFile: "file:open-markdown",
  listRecentFiles: "file:list-recent",
  openRecentFile: "file:open-recent",
  createUntitledFile: "file:create-untitled",
  openDroppedMarkdownFile: "file:open-dropped-markdown",
  listExternalOpenRequests: "file:list-external-open-requests",
  openExternalFile: "file:open-external",
  discardExternalOpenRequest: "file:discard-external-open-request",
  activateFileSession: "file:activate-session",
  closeFileSession: "file:close-session",
  persistRecoverySession: "recovery:persist-session",
  restoreRecoverySession: "recovery:restore-session",
  openWorkspaceFolder: "workspace:open-folder",
  openWorkspaceFile: "workspace:open-file",
  renameWorkspaceFile: "workspace:rename-file",
  renameOpenFile: "file:rename-open",
  saveCurrentFile: "file:save-current",
  saveCurrentFileAs: "file:save-current-as",
  selectAndImportImages: "image:select-and-import",
  importDroppedImages: "image:import-dropped",
  commitParse: "document:commit-parse",
  resolveResources: "resource:resolve",
  previewDerivedUpdate: "preview:derived-update",
  beginOutput: "output:begin",
  approveOutputOmissions: "output:approve-omissions",
  cancelOutput: "output:cancel",
  copyWechatReplacement: "output:wechat-copy-replacement",
  createWechatDraft: "output:wechat-create-draft",
  publishWechatArticle: "output:wechat-publish-article",
  getWechatApiConfig: "config:wechat-api-get",
  testWechatApiConnection: "config:wechat-api-test-connection",
  saveWechatApiConfig: "config:wechat-api-save",
  selectWechatCover: "config:wechat-cover-select",
  clearWechatApiConfig: "config:wechat-api-clear",
  saveWechatAcceptanceReport: "output:wechat-save-acceptance-report",
  listWechatThemes: "theme:wechat-list",
  resolveWechatThemeForPreview: "theme:wechat-resolve-preview",
  saveWechatThemeAsCustom: "theme:wechat-save-custom",
  deleteWechatTheme: "theme:wechat-delete",
  exportWechatTheme: "theme:wechat-export",
  importWechatTheme: "theme:wechat-import",
} as const;

export const FANTASTIC_EDITOR_LIMITS = Object.freeze({
  maxSourceCharacters: 10_000_000,
  maxMarkdownFileBytes: 40 * 1024 * 1024,
  maxResourceReferences: 10_000,
  maxSingleResourceBytes: 50 * 1024 * 1024,
  maxUniqueResolutionBytes: 200 * 1024 * 1024,
  maxFormulaRendersPerOutput: 500,
  maxMermaidRendersPerOutput: 100,
});
